version: "3.9"

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: flats_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d flats_db -U django"]
      interval: 2s
      timeout: 2s
      retries: 10    
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    command: sh -c "scrapy crawl flats | python /sreality_crawler/crawl_result/manage.py runserver 0.0.0.0:8080"  
    volumes:
      - .:/sreality_crawler
    
